import os, sys, shutil

shutil.copytree('./train/clutter/segment1','./benchmark1/clutter/train/task1')
shutil.copytree('./train/clutter/segment2','./benchmark1/clutter/train/task2')
shutil.copytree('./train/clutter/segment3','./benchmark1/clutter/train/task3')
shutil.copytree('./train/clutter/segment4','./benchmark1/clutter/train/task4')
shutil.copytree('./train/clutter/segment5','./benchmark1/clutter/train/task5')
shutil.copytree('./train/clutter/segment6','./benchmark1/clutter/train/task6')
shutil.copytree('./train/clutter/segment7','./benchmark1/clutter/train/task7')
shutil.copytree('./train/clutter/segment8','./benchmark1/clutter/train/task8')
shutil.copytree('./train/clutter/segment9','./benchmark1/clutter/train/task9')

shutil.copytree('./train/illumination/segment1','./benchmark1/illumination/train/task1')
shutil.copytree('./train/illumination/segment2','./benchmark1/illumination/train/task2')
shutil.copytree('./train/illumination/segment3','./benchmark1/illumination/train/task3')
shutil.copytree('./train/illumination/segment4','./benchmark1/illumination/train/task4')
shutil.copytree('./train/illumination/segment5','./benchmark1/illumination/train/task5')
shutil.copytree('./train/illumination/segment6','./benchmark1/illumination/train/task6')
shutil.copytree('./train/illumination/segment7','./benchmark1/illumination/train/task7')
shutil.copytree('./train/illumination/segment8','./benchmark1/illumination/train/task8')
shutil.copytree('./train/illumination/segment9','./benchmark1/illumination/train/task9')

shutil.copytree('./train/pixel/segment1','./benchmark1/pixel/train/task1')
shutil.copytree('./train/pixel/segment2','./benchmark1/pixel/train/task2')
shutil.copytree('./train/pixel/segment3','./benchmark1/pixel/train/task3')
shutil.copytree('./train/pixel/segment4','./benchmark1/pixel/train/task4')
shutil.copytree('./train/pixel/segment5','./benchmark1/pixel/train/task5')
shutil.copytree('./train/pixel/segment6','./benchmark1/pixel/train/task6')
shutil.copytree('./train/pixel/segment7','./benchmark1/pixel/train/task7')
shutil.copytree('./train/pixel/segment8','./benchmark1/pixel/train/task8')
shutil.copytree('./train/pixel/segment9','./benchmark1/pixel/train/task9')

shutil.copytree('./train/occlusion/segment1','./benchmark1/occlusion/train/task1')
shutil.copytree('./train/occlusion/segment2','./benchmark1/occlusion/train/task2')
shutil.copytree('./train/occlusion/segment3','./benchmark1/occlusion/train/task3')
shutil.copytree('./train/occlusion/segment4','./benchmark1/occlusion/train/task4')
shutil.copytree('./train/occlusion/segment5','./benchmark1/occlusion/train/task5')
shutil.copytree('./train/occlusion/segment6','./benchmark1/occlusion/train/task6')
shutil.copytree('./train/occlusion/segment7','./benchmark1/occlusion/train/task7')
shutil.copytree('./train/occlusion/segment8','./benchmark1/occlusion/train/task8')
shutil.copytree('./train/occlusion/segment9','./benchmark1/occlusion/train/task9')

shutil.copytree('./test/clutter/segment1','./benchmark1/clutter/test/task1')
shutil.copytree('./test/clutter/segment2','./benchmark1/clutter/test/task2')
shutil.copytree('./test/clutter/segment3','./benchmark1/clutter/test/task3')
shutil.copytree('./test/clutter/segment4','./benchmark1/clutter/test/task4')
shutil.copytree('./test/clutter/segment5','./benchmark1/clutter/test/task5')
shutil.copytree('./test/clutter/segment6','./benchmark1/clutter/test/task6')
shutil.copytree('./test/clutter/segment7','./benchmark1/clutter/test/task7')
shutil.copytree('./test/clutter/segment8','./benchmark1/clutter/test/task8')
shutil.copytree('./test/clutter/segment9','./benchmark1/clutter/test/task9')

shutil.copytree('./test/illumination/segment1','./benchmark1/illumination/test/task1')
shutil.copytree('./test/illumination/segment2','./benchmark1/illumination/test/task2')
shutil.copytree('./test/illumination/segment3','./benchmark1/illumination/test/task3')
shutil.copytree('./test/illumination/segment4','./benchmark1/illumination/test/task4')
shutil.copytree('./test/illumination/segment5','./benchmark1/illumination/test/task5')
shutil.copytree('./test/illumination/segment6','./benchmark1/illumination/test/task6')
shutil.copytree('./test/illumination/segment7','./benchmark1/illumination/test/task7')
shutil.copytree('./test/illumination/segment8','./benchmark1/illumination/test/task8')
shutil.copytree('./test/illumination/segment9','./benchmark1/illumination/test/task9')

shutil.copytree('./test/pixel/segment1','./benchmark1/pixel/test/task1')
shutil.copytree('./test/pixel/segment2','./benchmark1/pixel/test/task2')
shutil.copytree('./test/pixel/segment3','./benchmark1/pixel/test/task3')
shutil.copytree('./test/pixel/segment4','./benchmark1/pixel/test/task4')
shutil.copytree('./test/pixel/segment5','./benchmark1/pixel/test/task5')
shutil.copytree('./test/pixel/segment6','./benchmark1/pixel/test/task6')
shutil.copytree('./test/pixel/segment7','./benchmark1/pixel/test/task7')
shutil.copytree('./test/pixel/segment8','./benchmark1/pixel/test/task8')
shutil.copytree('./test/pixel/segment9','./benchmark1/pixel/test/task9')

shutil.copytree('./test/occlusion/segment1','./benchmark1/occlusion/test/task1')
shutil.copytree('./test/occlusion/segment2','./benchmark1/occlusion/test/task2')
shutil.copytree('./test/occlusion/segment3','./benchmark1/occlusion/test/task3')
shutil.copytree('./test/occlusion/segment4','./benchmark1/occlusion/test/task4')
shutil.copytree('./test/occlusion/segment5','./benchmark1/occlusion/test/task5')
shutil.copytree('./test/occlusion/segment6','./benchmark1/occlusion/test/task6')
shutil.copytree('./test/occlusion/segment7','./benchmark1/occlusion/test/task7')
shutil.copytree('./test/occlusion/segment8','./benchmark1/occlusion/test/task8')
shutil.copytree('./test/occlusion/segment9','./benchmark1/occlusion/test/task9')
