python3 main.py --factor=clutter --ewc --savepath='./results/clutter/ewc/'
python3 main.py --factor=clutter --ewc --online --savepath='./results/clutter/ewc_online/'
python3 main.py --factor=clutter --savepath='./results/clutter/naive/'
python3 main.py --factor=clutter --si --savepath='./results/clutter/si/'
python3 main.py --factor=clutter --cumulative=1 --savepath='./results/clutter/cumulative/'
python3 main.py --factor=clutter --replay=current --savepath='./results/clutter/lwf/'
python3 main.py --factor=clutter --replay=generative --distill --savepath='./results/clutter/dgr_distill/'
python3 main.py --factor=clutter --replay=generative --savepath='./results/clutter/dgr/'
python3 main.py --factor=clutter --replay=generative --distill --feedback --savepath='./results/clutter/dgr_distill_feedback/'