python3 main.py --factor=illumination --ewc --savepath='./results/illumination/ewc/'
python3 main.py --factor=illumination --ewc --online --savepath='./results/illumination/ewc_online/'
python3 main.py --factor=illumination --savepath='./results/illumination/naive/'
python3 main.py --factor=illumination --si --savepath='./results/illumination/si/'
python3 main.py --factor=illumination --cumulative=1 --savepath='./results/illumination/cumulative/'
python3 main.py --factor=illumination --replay=current --savepath='./results/illumination/lwf/'
python3 main.py --factor=illumination --replay=generative --distill --savepath='./results/illumination/dgr_distill/'
python3 main.py --factor=illumination --replay=generative --savepath='./results/illumination/dgr/'
python3 main.py --factor=illumination --replay=generative --distill --feedback --savepath='./results/illumination/dgr_distill_feedback/'