python3 main.py --factor=occlusion --ewc --savepath='./results/occlusion/ewc/'
python3 main.py --factor=occlusion --ewc --online --savepath='./results/occlusion/ewc_online/'
python3 main.py --factor=occlusion --savepath='./results/occlusion/naive/'
python3 main.py --factor=occlusion --si --savepath='./results/occlusion/si/'
python3 main.py --factor=occlusion --cumulative=1 --savepath='./results/occlusion/cumulative/'
python3 main.py --factor=occlusion --replay=current --savepath='./results/occlusion/lwf/'
python3 main.py --factor=occlusion --replay=generative --distill --savepath='./results/occlusion/dgr_distill/'
python3 main.py --factor=occlusion --replay=generative --savepath='./results/occlusion/dgr/'
python3 main.py --factor=occlusion --replay=generative --distill --feedback --savepath='./results/occlusion/dgr_distill_feedback/'