python3 main.py --factor=pixel --ewc --savepath='./results/pixel/ewc/'
python3 main.py --factor=pixel --ewc --online --savepath='./results/pixel/ewc_online/'
python3 main.py --factor=pixel --savepath='./results/pixel/naive/'
python3 main.py --factor=pixel --si --savepath='./results/pixel/si/'
python3 main.py --factor=pixel --cumulative=1 --savepath='./results/pixel/cumulative/'
python3 main.py --factor=pixel --replay=current --savepath='./results/pixel/lwf/'
python3 main.py --factor=pixel --replay=generative --distill --savepath='./results/pixel/dgr_distill/'
python3 main.py --factor=pixel --replay=generative --savepath='./results/pixel/dgr/'
python3 main.py --factor=pixel --replay=generative --distill --feedback --savepath='./results/pixel/dgr_distill_feedback/'